plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Spring Boot Command Line Application'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation platform('org.springframework.boot:spring-boot-dependencies:4.1.1')

	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
